  export const response = [
  {
    id: 'final-libertadores-2020',
    title: 'Libertadores',
    subtitle: 'Final | Rio de Janeiro',
    categories: ['Brasil'],
    date: 'Janeiro/2021',
    img: '/img/final-libertadores-2020-capa-md.png',
    href: '/evento/final-libertadores-2020',
  },
  {
    id: 'open-rio-2021',
    title: 'Rio Open',
    subtitle: 'Rio de Janeiro',
    categories: ['Brasil'],
    date: '15/02 a 21/02/21',
    img: '/img/final-rio-open-2021-capa-md.png',
    href: '/evento/rio-open-2021',
  },
  {
    id: 'miami-open-2021',
    title: 'Miami Open',
    subtitle: 'Miami',
    categories: ['internacional'],
    date: '22/03 a 04/04/21',
    img: '/img/capa-miami-open-2021-md.png',
    href: '/evento/miami-open-2021',
  },
  {
    id: 'final-champions-league-2021',
    title: 'Champions League',
    subtitle: 'Final | Istambul',
    categories: ['internacional'],
    date: '29/05/21',
    img: '/img/final-champions-league-2021-md.png',
    href: '/evento/final-champions-league-2021',
  },  
  {
    id: 'olimpiada-toquio-2021',
    title: 'Jogos Olímpicos',
    subtitle: 'Tóquio',
    categories: ['internacional'],
    date: '23/07 a 08/08/21',
    img: '/img/olimpiada-toquio-2021-md.png',
    href: '/evento/olimpiada-toquio-2021',
  },  
  {
    id: 'us-open-2021',
    title: 'US Open',
    subtitle: 'Nova Iorque',
    categories: ['internacional'],
    date: '30/08 a 12/09/21',
    img: '/img/us-open-2021-md.png',
    href: '/evento/us-open-2021',
  },
  {
    id: 'copa-do-mundo-2022',
    title: 'Copa do Mundo 2022',
    subtitle: 'Qatar',
    categories: ['internacional'],
    date: '21/11 a 18/12/22',
    img: '/img/copa-do-mundo-2022-md.png',
    href: '/evento/copa-do-mundo-2022',
  },
];
