export const response = [
  {
    id: 'libertadores',
    title: 'Libertadores',
    categories: ['nacional'],
    date: '02 à 14 de Setembro 2020',
    img: 'https://mercedesbenzstadium.com/wp-content/uploads/2017/09/20170916_atlutd_orlandocity_kh-175-1.jpg',
    href: '/evento',
  },
  {
    id: 'olimpiadas',
    title: 'Olimpíadas 2020',
    categories: ['internacional'],
    date: '02 à 14 de Setembro 2020',
    img: 'https://api.time.com/wp-content/uploads/2018/02/puerto-rico-winter-olympics.jpg',
    href: '/evento',
  },
  {
    id: 'us-open',
    title: 'US Open',
    categories: ['internacional', 'nacional'],
    date: '02 à 14 de Setembro 2020',
    img: 'https://thenypost.files.wordpress.com/2020/03/us-open-tennis.jpg?quality=80&strip=all',
    href: '/evento',
  },
  {
    id: 'final-copa',
    title: 'Final Copa',
    categories: ['internacional'],
    date: '02 à 14 de Setembro 2020',
    img: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Bra-Cos_%282%29.jpg',
    href: '/evento',
  },
  {
    id: 'copa-do-mundo',
    title: 'Copa do Mundo',
    categories: ['internacional'],
    date: '02 à 14 de Setembro 2020',
    img: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Bra-Cos_%282%29.jpg',
    href: '/evento',
  },
];
